#!/usr/bin/env bash

# stop and remove the docker container

source .env
#export $(grep --regexp ^[a-z] .env | cut -d= -f1)

#docker container exec $cname /opt/Unity/Editor/Unity -batchmode -nographics -quit -serial SC-B5MY-2GF6-6BB2-NS68-JW9M -username 'armando@neurasights.com' -password '' -returnlicense
docker container stop $cname
docker container rm $cname

